### ISSUE TITLE
Make GitHub API URL configurable to support GitHub Enterprise Server

### ISSUE THREAD

**Issue by artis3n** [self-actuated/actions-usage#14]
The APIs should be all the same, just let you define your own GitHub server URL. I'll put up a PR later, as long as no one is opposed to this.

**Comment by alexellis** [comment]
Hey @artis3n / @halkeye, I just saw your PR. Are you thinking of using our tool at DigitalOcean?

Alex

**Comment by artis3n** [comment]
@alexellis Just poking at it out of curiosity!
