### ISSUE TITLE
Nil pointer dereference error with organisation

### ISSUE THREAD

**Issue by MattMencel** [self-actuated/actions-usage#17]
I've attempted to run this against my org from my mac laptop and from a linux container and get the same segmentation violation.

```
actions-usage  --org MYORG  --token-file ~/pat.txt  --days 1

2023/10/30 19:35:52 Fetching jobs for: run ID: 6697773061, startedAt: 2023-10-30 19:27:54, conclusion:
2023/10/30 19:35:52 Fetching jobs for: 6697773061, page 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x65a180]

goroutine 1 [running]:
main.main()
	/home/runner/work/actions-usage/actions-usage/main.go:238 +0x30e0
```

**Comment by alexellis** [comment]
Hey @MattMencel which version are you using?

238 doesn't seem like the right line for a nil pointer:

https://github.com/self-actuated/actions-usage/blob/master/main.go#L238C1-L239C1

Do you have Actions enabled on your repos? And a valid PAT?

I just ran: `actions-usage --org inlets --token-file ./PAT.txt --days 1` which passed as expected, so maybe there's something different about your configuration or builds?

**Comment by alexellis** [comment]
/set title: Nil pointer dereference error with organisation

**Comment by MattMencel** [comment]
Hi @alexellis, see below. It's the latest version. Now it reports line 254.

I refreshed the PAT and made sure it had `repo` and `admin:org` scopes.

```
> arkade get actions-usage
Downloading: actions-usage
2023/11/10 15:22:07 Looking up version for actions-usage
2023/11/10 15:22:07 Found: v0.1.0
...
# Test the binary:
/Users/matt.mencel/.arkade/bin/actions-usage
```

```sh
> ~/.arkade/bin/actions-usage  --org myorg  --token-file pat.txt  --days 1
Fetching last 1 days of data (created>=2023-11-09)
2023/11/10 15:21:20 Fetching repos myorg page 0
2023/11/10 15:21:21 Status: 200 Page 0, next page: 2
2023/11/10 15:21:21 Fetching repos myorg page 2
2023/11/10 15:21:21 Status: 200 Page 2, next page: 0
2023/11/10 15:21:21 Found: myorg/firstrepo
2023/11/10 15:21:21 Listing workflow runs for: myorg/firstrepo
2023/11/10 15:21:23 Listing workflow runs for: myorg/firstrepo
2023/11/10 15:21:26 Listing workflow runs for: myorg/firstrepo
2023/11/10 15:21:28 Listing workflow runs for: myorg/firstrepo
2023/11/10 15:21:32 Listing workflow runs for: myorg/firstrepo
2023/11/10 15:21:33 Found 454 workflow runs for myorg/server
2023/11/10 15:21:33 Fetching jobs for: run ID: 6829614058, startedAt: 2023-11-10 21:07:11, conclusion:
2023/11/10 15:21:33 Fetching jobs for: 6829614058, page 0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10073b8a4]

goroutine 1 [running]:
main.main()
	/home/runner/work/actions-usage/actions-usage/main.go:254 +0x2984
```

Does the `go` version matter?
```
> go version 
go version go1.21.4 darwin/arm64
```

**Comment by alexellis** [comment]
Thanks for the info. Assuming you've now updated to the latest version, errors from that line are about matching on the latest version:

https://github.com/self-actuated/actions-usage/blob/master/main.go#L254C1-L255C1

Unfortunately, we can't reproduce the issue running against other open source or private organisations.

The only thing I can suggest is that we try to add some defensive coding around accessing variables that may be nil.

@Jasstkn @Shikachuu could you take a look and see what you think?

**Comment by alexellis** [comment]
This release may show us the culprit repo  I know you're being secretive with your organisation name), but it may help show you what's different.

Either it's not being detected in your total list of repositories in the organisation, and therefore has no summary pre-populated, or it's a repo that was deleted, but has actions runs history. Let's see if we can find out.

https://github.com/self-actuated/actions-usage/releases/tag/v0.1.1

**Comment by MattMencel** [comment]
@alexellis hey it worked! Thanks!

**Comment by alexellis** [comment]
Glad to hear it 👍
