### ISSUE TITLE
How can I run this for a user account?

### ISSUE THREAD

**Issue by ljharb** [self-actuated/actions-usage#2]
`--org=ljharb`, for example, says user not found, which is confusing if it's org-only.

**Comment by alexellis** [comment]
Hi @ljharb it's designed for use with an org, see the write-up here:

https://blog.alexellis.io/github-actions-usage-build-minutes/

But you can hack on it and change the code, it wouldn't take much.

If you'd like to learn [how to do that kind of thing with Go, I have a book about it](https://blog.alexellis.io/i-wrote-a-book-about-golang/).

Alex

**Comment by ljharb** [comment]
Gotcha. This issue is really two items:
1. a bug, that i see "user not found" when providing a nonexistent org
1. a feature request for `--user`

**Comment by alexellis** [comment]
> a bug, that i see "user not found" when providing a nonexistent org

That sounds like correct behaviour?

> a feature request for --user

That should land within a day or two (@Jasstkn)

https://twitter.com/Jasstkn/status/1630842055063752705?s=20

**Comment by ljharb** [comment]
@alexellis if the argument is named `--org` and it only supports organizations, then the error message should say "organization not found" or similar. By saying the word "user", it suggests that the program supports *users* under the `--org` argument, which is confusing.

> That should land within a day or two

Awesome!!

**Comment by alexellis** [comment]
Unfortunately, we don't control the errors, they come from GitHub.

But we'll see if we can do anything to wrap it.
