### ISSUE TITLE
Pull the token from the environment

### ISSUE THREAD

**Issue by mahmoudhossam** [self-actuated/actions-usage#5]
Can we make the CLI pull the github token from an environment variable? Say `$GITHUB_TOKEN` so it's easier to run in a github actions workflow.

**Comment by alexellis** [comment]
Hey @mahmoudhossam 

How were you thinking of running the tool?

For the env-var, you can simply do it like this:

```bash
actions-usage --org openfaas --token $GITHUB_TOKEN
```

Does that help?

Alex

**Comment by mahmoudhossam** [comment]
@alexellis I was using the examples on the readme and I assumed it only worked using a file, but turns out that I can simply pass the env var itself.

The docs should reflect that but thanks for clarifying anyway!
